import cv2 as cv#type:ignore

FRAME_SKIP_START = 1
FRAME_COLLECTION_SKIP = 2
DRAMATIC_PIXEL_CHANGE = 200
DANGER_TRIGGER_REQUIREMENT = 8
PORTION_DATA_MAX_CAPACITY = 10

GIF_DETERMINER_MINFRAME = 80

TEST_DATA_DIR = 'testdata'

NO_PORTIONS, VERT_PORTIONS, HORIZ_PORTIONS = (8, 2, 4)

EPILEPSY_DETECTION_REACTIONS = ['🔺', '🇸', '🇪', '🇮', '🇿', '🇺', '🇷', '📸', '🔻']
